### ISSUE TITLE
API not working in local server

### ISSUE THREAD

**Issue by Santoxjon** [deliton/zelda-api#1]
Hi there,

I'm trying to use this wonderful API for a class project and whenever I try to build the project in local it gives no error message.

However, when trying to get data from the API, for example: **localhost:3000/api/games**
it gives me **INTERNAL SERVER ERROR**

**Comment by deliton** [comment]
It's because you need to set the env variables to match the MongoDB database. Do you really need to run this API locally?

**Comment by Santoxjon** [comment]
It'll be nice if I could run it locally since I got the 502 error very often and I think it is a problem of the remote server

**Comment by deliton** [comment]
Yeah, I know that. It happens because NextJS wasn't exactly planned to work as a backend connected to a database directly. I will soon release a v2 that will remove the need to check the database and instead use local JSON files, so you could run locally too.

**Comment by Santoxjon** [comment]
Ok I understand, nice work BTW. It would be damn cool if it had images but I guess you'll try to improve the API in the future. Keep coding bro, appreciate the work 😄

**Comment by deliton** [comment]
Thanks for the feedback! :smile:
