### ISSUE TITLE
Arrays return a url, not an array of objects

### ISSUE THREAD

**Issue by sebastinto** [deliton/zelda-api#2]
Hi there!

The documentation says that arrays should be returned as something like this:

```json
"appearances": [
                {
                    "_id": "5f6ce9d805615a85623ec2c0",
                    "name": "The Legend of Zelda: Oracle of Seasons"
                },
                {
                    "_id": "5f6ce9d805615a85623ec2c9",
                    "name": "The Legend of Zelda: Breath of the Wild"
                }
            ]
```
But what's actually returned is a url to another endpoint like this: 

```json
"appearances": [
                "https://zelda-api.apius.cc/api/games/5f6ce9d805615a85623ec2c8"
            ]
```

I don't know if it's intended and the doc hasn't been updated or if it's a bug. 

Anyhow, I just wanted to mention it and get clarification on the proper usage of the api. 

Thanks!

**Comment by deliton** [comment]
Hello @sebastinto! Sorry for taking too long to answer. Yeah, the documentation wasn't updated with this. I'll be pushing a fix to the docs, Thanks!

**Comment by deliton** [comment]
By the way, the API is way faster and supports GraphQL now ;)
